### ISSUE TITLE
Add option to exclude pinned tabs when selecting the main window

### ISSUE THREAD

**Issue by ocrete** [piroor/aggregate-tabs-to-main-window#10]
My use-case is that I have one main window and one with 8 different messaging applications in pinnned tabs. I want all the new tabs to go to the other window.

**Comment by piroor** [comment]
Sorry I cannot imagine what it should work as exactly... Could you describe with detailed steps to produce? For example:

1. Start Firefox.
2. Open two windows, assume A and B.
3. Open 8 tabs in the window B.
4. Pin all 8 tabs in the window B.
5. ...

then append both "expected result" and "actual (current) result".

**Comment by galantra** [comment]
I imagine he means:

If the tab was opened _from a pinned tab_, make the extension do nothing (noop).

**Comment by ocrete** [comment]
Sorry.  I expect

1.    Start Firefox.
2.    Open two windows, assume A and B.
3.    Open 8 tabs in the window B.
4.    Pin all 8 tabs in the window B.
5. Open one regular tab in window A

I expect any newly opened tab  would to moved to window A.

Ie, not take the pinned tabs into account when trying to find the main window. My usecase is that window B is on my secondary smaller monitor an is only for chat.. I want all normal tabs to get to window A

**Comment by piroor** [comment]
Thanks, I got it. I didn't think about cases with a sub window sized similar to the main window and having pinned tabs. I've introduced an option `countPinnedTabsToDetectMainWindow` and set it `false` by default with the commit ff11f25.
