### ISSUE TITLE
[Help or Feature Request] - Proper usage of options

### ISSUE THREAD

**Issue by SHHSSH** [piroor/aggregate-tabs-to-main-window#15]
Hi @piroor 

Just wondering if you could explain the "Don't aggregate if it is matched to the regular expression:" option.

Is this only allowing for 2 total exclusions? As I was unable to utilise commas within the input field for multiple exclusions and have only been able to exclude 2 domains maximum.

Is there a way to exclude more than 2 from being aggregated?

**Comment by piroor** [comment]
Did you try combination of `(...)` and `|` ? For example: 

`^https?://(www\.google\.com|mozilla\.org|github\.com)/`

This regex pattern will match all of followings:

* http://www.google.com/...
* https://www.google.com/...
* http://mozilla.org/...
* https://mozilla.org/...
* http://github.com/...
* https://github.com/...

**Comment by SHHSSH** [comment]
Thank you that works :)
