### ISSUE TITLE
Ver.1.2.1 doesn't work

### ISSUE THREAD

**Issue by array** [piroor/aggregate-tabs-to-main-window#2]
現象：
1.2.1をインストールしたところ、タブが集約されなくなった。
ブックマークサイドバーから、クリックするとそのサイドバーがあるウィンドウにブックマークサイトが開いてしまう。
ただし、サブウィンドウでのメニュー→アドオン・オプションなどはメインウィンドウに開く。
またサブウィンドウ内のリンクもメインウィンドウで開く。
環境：
Firefox 60.0.2
Windows10 64bit　1803
拡張：
https://arrayszk.blogspot.com/2018/06/firefox.html
を参照していただければ幸いです。

**Comment by piroor** [comment]
初期設定では、タブとして開かれた物だけがメインウィンドウに移動され、サブウィンドウの現在のタブに読み込まれた内容はそのまま現在のタブに読み込まれるようになっています。
ブックマークから常に新しいタブを開くようにするには、about:configでbrowser.tabs.loadBookmarksInTabsをtrueにする必要がありますが、このような設定がない機能に対しては、明示的にミドルクリック等でタブを開く使い方をしていただく必要があります。

そうではなく、タブで開いた物が移動されないということでしょうか？
であれば、こちらの環境では現象を再現できませんでした。
他のアドオンと干渉している可能性がありますが、どれと干渉しているかをこちらで調べるのは大変なので、そこの特定にご協力いただければ幸いです。

ちなみに「ロケーションバーから新しいタブを開く」はFirefox 61では本体の機能でほぼ代替可能なので、アドオンとしての開発は終了して、現在はメンテナンスできていない状態です（モチベーションが低い）。
ESRにする必然性が無いのであれば、Firefox 61以降を使われる事をお薦めしたい所です。

**Comment by array** [comment]
了解しました。about:configで変更したところ、動作しました。
Firefox Developerが若干暴走気味だったのでRelease（60.0.2）に変更したところでした。自分で設定をしていたのですね。
61を使ったほうが良いのであればDeveloperか、Betaに変えてみます。ありがとうございました。
